#!python3

import json
import sys
from urllib import request

RPC = 'http://localhost:6800/jsonrpc'
PRESET_OPTS = { 'continue': 'true', 'max-connection-per-server': 16, 'split': 16, 'min-split-size': '1M',
								'user-agent': 'netdisk;5.5.2.0;PC;PC-Windows;10.0.14393;WindowsBaiduNetdisk',
								'referer': 'http://pan.baidu.com/disk/home'}

def download(urls, fname):
	jsondict = {'jsonrpc':'2.0', 'id':'aria2rpc', 'method':'aria2.addUri', 'params':[urls]}
	aria2opts = PRESET_OPTS
	aria2opts['out'] = fname
	jsondict['params'].append(aria2opts)
	jsonreq = json.dumps(jsondict).encode('utf-8')
	request.urlopen(RPC, jsonreq)

def getBDLink(url):
	if len(url) == 8:
		return 'https://pan.baidu.com/s/' + url
	else:
		return 'https://' + url[url.index('pan.'):]

def normalize(fname):
	i = fname.find('RJ')
	o = fname.rfind('.')
	ext = fname[o:]
	if i > -1 and fname[i+2:i+8].isdigit():
		return fname[i:i+8] + ext
	if o == 6 and fname[:6].isdigit():
		return 'RJ' + fname[:6] + ext
	return fname

argc = len(sys.argv)
if argc == 1:
	print('Usage bdp url pw')
	sys.exit(1)
longFlag = 2 if sys.argv[1].find('链接') > -1 else 1
link = 'http://api.pescn.top/sharelinks?shareurl=' + getBDLink(sys.argv[longFlag])
if argc > longFlag * 2:
	link += '&pass=%s' % sys.argv[-1][-4:]
resp = json.loads(request.urlopen(link).read())
print('Error Number: %s' % resp['errno'])
print('Error Message: %s' % resp['message'])
for fname in resp['links'].keys():
	print('Start download %s' % fname)
	download(resp['links'][fname], normalize(fname))
